### ISSUE TITLE
Commands not recognized

### ISSUE THREAD

**Issue by timLinscott** [DevInsideYou/sublime-spotify-rest#1]
I've installed this package in Sublime Text 3 (build 3126) on Ubuntu 16.04.2, I registered the app and added the ID and secret to the settings file. Package Control recognizes SpotifyWeb as an installed package, but I didn't get an install message and I can't run any of the commands. When I attempt to run the `spotify_web_toggle` and `spotify_web_settings` commands from the console, I get 
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'spotify_web_settings' is not defined`

I noticed that this package was originally designed on Windows. Is Linux not supported? Or is there a critical installation step I missed?

**Comment by agilesteel** [comment]
Hi,

that was fast. I just released it yesterday :)

It should work on all platforms. In fact it was developed under Ubuntu 16.

Sublime zips some packages, but I told packagecontrol explicitly to not zip it, so it should be under `~/.config/sublime-text-3/Packages/SpotifyWeb`. Do you see it there?

Don't hesitate to ask further. It should work!

**Comment by timLinscott** [comment]
All the files are there, and nothing seems to be zipped.

**Comment by agilesteel** [comment]
How does your `~/.config/sublime-text-3/Packages/User/SpotifyWeb.sublime-settings` file look like? Don't send me your keys obviously.

Btw, you are not supposed to run the commands from the console. Just go to command palette with Ctrl+Shift+P and start typing SpotifyWeb or go to Preferenses -> Package Settings -> SpotifyWeb

**Comment by timLinscott** [comment]
I had to run the commands from the console and open the settings file manually, because the command pallet doesn't recognize the commands (as the Python error corroborates).  

`SpotifyWeb.sublime-settings` doesn't exist in the `Packages/User` directory.

**Comment by agilesteel** [comment]
So when you installed it, the first thing that should have happened was another instance of sublime opening with the `Packages/SpotifyWeb/SpotifyWeb.sublime-settings` on the left and `Packages/User/SpotifyWeb.sublime-settings` on the right. I guess you saw that, since you knew that you needed to register an app. If the file doesn't exist in the User directory I assume you modified that default settings file, which is not ideal but still doesn't explain why it didn't work.

Your `Packages/User/SpotifyWeb.sublime-settings` file should look sth like that

```json
{
  "SpotifyWeb_string_client_id": "your id",
  "SpotifyWeb_string_client_secret": "your secret",
  "SpotifyWeb_bool_is_enabled": true
}
```
If none of that happened then sth went wrong during the installation... What's in the console if you open it right after restarting sublime?

**Comment by timLinscott** [comment]
I didn't get the initial pop-up. And, yes, I modified the default settings. 

Here's the start-up error:
reloading plugin SpotifyWeb.SpotifyWeb
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/timlinsc/.config/sublime-text-3/Packages/SpotifyWeb/SpotifyWeb.py", line 5, in <module>
    from .src.spotify.Spotify import Spotify
  File "/home/timlinsc/.config/sublime-text-3/Packages/SpotifyWeb/src/spotify/Spotify.py", line 4, in <module>
    from .Client import Client
  File "/home/timlinsc/.config/sublime-text-3/Packages/SpotifyWeb/src/spotify/Client.py", line 6, in <module>
    from ...lib.spotipy import oauth2 as SpotipyOauth2
  File "/home/timlinsc/.config/sublime-text-3/Packages/SpotifyWeb/lib/spotipy/oauth2.py", line 13, in <module>
    import urllib.parse as urllibparse
AttributeError: 'module' object has no attribute 'parse'

**Comment by agilesteel** [comment]
Try this: open ~/.config/sublime-text-3/Packages/SpotifyWeb/lib/spotipy/oauth2.py with some editor.

And comment out lines 10-14 (inclusive) then indent line 15 to the beginning of the line. It should look like this:

```python
# Workaround to support both python 2 & 3
# try:
#     import urllib.request, urllib.error
#     import urllib.parse as urllibparse
# except ImportError:
import urllib as urllibparse
```

**Comment by agilesteel** [comment]
Then restart sublime and tell me what's in the console

**Comment by timLinscott** [comment]
That cleared the error and created the settings file under `User/`. 

But... I'm still not actually getting output to status bar. Can you clarify the usage?

**Comment by agilesteel** [comment]
Sure, so if there are no errors in the console and the plugin is enabled then your browser should open and you log in to your Spotify account and allow your app to access your account. If that goes well you should see the currently playing song in the taskbar. Note that the rest endpoint that the plugin is using is not updated by all clients. Try with https://play.spotify.com first

**Comment by agilesteel** [comment]
I meant status bar :) Let me know if it worked!

**Comment by timLinscott** [comment]
I opened Spotify in Chrome (there should not have been a special pop-up for that, should there have been?). The status bar is now perpetually displaying "'module' object has no attribute 'urlencode'"

**Comment by agilesteel** [comment]
I'm using spotipy (with a p) for oauth2 and somehow it causes trouble on your end. I've never seen this before. I have it working on windows and ubuntu 16 as well. It's normal behavior btw that it forwards all exceptions to the status bar...

Could you verify that you have a folder called "requets"  in  ~/.config/sublime-text-3/Package and also restart sublime one more time and tell me what's in the console. I need to see the file and line number where the error occurs... Thanks

**Comment by agilesteel** [comment]
Ok I'm at home now and I did some digging.

Sublime is using python 3.3.6 (you can verify that when typing the following in the console)

```python
import sys
sys.version
```

The exception is coming for this function https://docs.python.org/3.3/library/urllib.parse.html#urllib.parse.urlencode which should be imported in python 3.3.6 as `import urllib.parse as urllibparse`  which was in `oauth2.py` in line 13, but somehow it was failing for you so we tried commenting it out...

Try this as an import in `oauth2.py`

```python
from urllib.parse import urlparse as urllibparse
```

instead of either of the following 2

```python
import urllib.parse as urllibparse
```

```python
import urllib as urllibparse
```

**Comment by agilesteel** [comment]
Strangely enough, all of these imports work for me...

**Comment by timLinscott** [comment]
`import urllib as urllibparse` wasn't throwing any errors, but I tried `from urllib.parse import urlparse as urllibparse` instead. Now I have " 'function' object has no attribute 'urlencode' " as the status bar message.

**Comment by timLinscott** [comment]
And, yes, I'm using Python 3.3.6.

**Comment by agilesteel** [comment]
Strange... I'm on Ubuntu 16.04.3 and have the same version of sublime text as you 3126... As of right now I don't have any more suggestions :( I'll keep looking though

**Comment by agilesteel** [comment]
I just downloaded the source for python 3.3.6 and made a screenshot of `urllib/parse.py`. The way `urlencode` is called in `oauth2.py`, this should be the right way to import it: `import urllib.parse as urllibparse` but it raises an exception for you and I have no idea why :(

![source](https://user-images.githubusercontent.com/1141462/29529567-7b0b4d3a-86a0-11e7-81f0-9210944b0bb7.png)

**Comment by agilesteel** [comment]
I'm seeing issues with this all over the internet, but no solution except for fixing the imports... Look at this for example https://github.com/omgovich/sublime-typograf/issues/1 it's even related to sublime

**Comment by agilesteel** [comment]
This answer https://stackoverflow.com/questions/33206536/import-urllib-parse-fails-when-python-run-from-command-line says that `urllib` itself should be imported before `urllib.parse`... Maybe you can try that...

**Comment by timLinscott** [comment]
There's definitely some kind of confusion between urllib and urllib.parse and the Python 2.7 vs 3.3 versions where they split up urllib. Preliminary tests say I don't have any issues when I run the oauth code on the command line, just in Sublime. I'll keep looking into this later.
